from pptx import Presentation


class PresentationService:

    @staticmethod
    def create_presentation(topic: str):

        presentation = Presentation()

        slide = presentation.slides.add_slide(
            presentation.slide_layouts[0]
        )

        slide.shapes.title.text = topic

        slide.placeholders[1].text = (
            "Generated by AI Enterprise Platform"
        )

        file_name = (
            topic.replace(" ", "_")
            .lower()
            + ".pptx"
        )

        file_path = (
            f"app/generated_files/{file_name}"
        )

        presentation.save(file_path)

        return file_path